version: "2"
services:
  express:
    container_name: express-server
    build:
      context: .
      dockerfile: ./express-server/Dockerfile
    volumes:
      - ./express-server/app:/usr/src/app
    ports:
      - "8080:8080"
    links:
      - mongodb
      
  angular:
    container_name: angular-client
    build:
      context: .
      dockerfile: ./angular-client/Dockerfile
    volumes:
      - ./angular-client/app:/usr/src/app
    ports:
      - "4200:4200"
      
  mongodb:
    container_name: mongodb-database
    image: mongo:latest
    ports:
      - "27017:27017"
